extends Node
class_name TRICKS

enum VAR {
	JUGGLE_BASTON,
	JUGGLE_ANTORCHA,
	JUGGLE_CUCHILLO,
	MONOCYCLE,
	CAKE_SHOTS,
	ROPE,
}

const NAMES = {
	VAR.JUGGLE_BASTON: "Baston",
	VAR.JUGGLE_ANTORCHA: "Antorcha",
	VAR.JUGGLE_CUCHILLO: "Cuchillo",
	VAR.MONOCYCLE: "Monocyclo",
	VAR.CAKE_SHOTS: "Cake Shots",
	VAR.ROPE: "Tightrope",
}

const HANDEABLE = [
	VAR.JUGGLE_BASTON,
	VAR.JUGGLE_ANTORCHA,
	VAR.JUGGLE_CUCHILLO,
]

const EASY_TRICKS = [
	VAR.JUGGLE_BASTON,
]

const MEDIUM_TRICKS = [
	VAR.JUGGLE_ANTORCHA,
	VAR.MONOCYCLE,
	VAR.CAKE_SHOTS,
]

const HARD_TRICKS = [
	VAR.JUGGLE_CUCHILLO,
	VAR.ROPE,
]
